### ISSUE TITLE
请教一下文章的缓存

### ISSUE THREAD

**Issue by vesugier** [emako/SG.Plugin.Drop.Wish#1]
你好，我想请教一下[这篇文章](https://github.com/emako/SG.Plugin.Drop.Wish/blob/1.0.1/doc/README.md)是通过什么程序或者项目进行的缓存，我平常用的html存储，但是源码的可读性以及二次编辑远不如MD格式，特此提出issue，望回复

**Comment by emako** [comment]
咱是Typora玩家
